name: YariUserTracker
main: com.yaricraft.YariUserTracker.YariUserTracker
version: 0.0.1
commands:
   yut:
      description: This is a demo command.
      usage: /<command>
      permission: usertracker.yut
      permission-message: You don't have permission to use YariUserTracker.
permissions:
   usertracker.yut:
      description: Gives access to all YariUserTracker commands.
      default: true